---
title: "Meekness: Characters and Qualities"
output: html_notebook
---

## Settings

```{r}
options(connectionObserver = NULL)

library(DBI, quietly = TRUE)
library(odbc, quietly = TRUE)

library(ggplot2)
library(scales)
library(grid)
library(gridExtra)

setwd('/path/to/working/directory')

seabornPalette <- c("#4c72b0","#55a868","#c44e52","#8172b2","#ccb974","#64b5cd","#4c72b0","#55a868",
                    "#c44e52","#8172b2","#ccb974","#64b5cd","#4c72b0","#55a868","#c44e52","#8172b2",
                    "#ccb974","#64b5cd","#4c72b0","#55a868","#c44e52","#8172b2","#ccb974","#64b5cd",
                    "#4c72b0","#55a868","#c44e52","#8172b2","#ccb974","#64b5cd","#4c72b0","#55a868",
                    "#c44e52","#8172b2","#ccb974","#64b5cd","#4c72b0","#55a868","#c44e52","#8172b2",
                    "#ccb974","#64b5cd","#4c72b0","#55a868","#c44e52","#8172b2","#ccb974","#64b5cd",
                    "#4c72b0","#55a868","#c44e52","#8172b2","#ccb974","#64b5cd","#4c72b0","#55a868",
                    "#c44e52","#8172b2","#ccb974","#64b5cd")

# RETRIEVE DATA FROM SQL SERVER
retrieve_data <- function(sql) {
  conn <- dbConnect(odbc::odbc(), driver = "ODBC Driver 17 for SQL Server",
                    server = "****", port = 1433, database = "****",
                    uid = "****", pwd = "****")
  sql_df <- dbGetQuery(conn, sql)
  dbDisconnect(conn)
  
  return(sql_df)
}

```

## Top 10 Matched Characters

```{r, fig.width=10, fig.height=5}
strSQL <- paste("WITH cte AS (",
                "  SELECT c.[ID], c.[Character], q.[Quality]",
                "  FROM [Characters] c" , 
                "  INNER JOIN [Qualities] q ON c.ID = q.CharacterID",
                "  ",
                ")",
                "",
                "SELECT TOP 10 c1.Character,",
                "       SUM(CASE WHEN c1.Quality = c2.Quality THEN 1 ELSE 0 END) AS MatchCount", 
                "FROM cte As c1",
                "CROSS JOIN cte As c2",
                "WHERE c1.ID < c2.ID",
                " ",
                "GROUP BY c1.Character",
                "ORDER BY SUM(CASE WHEN c1.Quality = c2.Quality THEN 1 ELSE 0 END) DESC")
                           
char_df <- retrieve_data(strSQL)
char_df <- within(char_df, Character <- factor(Character, levels=Character[order(-MatchCount)]))

ggplot(char_df[1:10,], aes(Character, MatchCount, fill=Character)) + 
  geom_col(width=0.5) + 
  labs(title="Top 10 Matched Characters", y="Counts") + guides(fill=FALSE) +
  scale_fill_manual(values = seabornPalette) +
  scale_y_continuous(expand = c(0, 0), limits=c(0,150)) +
  theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 23, hjust = 1))
```


## Top 10 Works Types

```{r, fig.width=10, fig.height=5}
strSQL <-  strSQL <- paste("WITH cte AS (",
                           "  SELECT c.[ID], c.[Character], q.[Quality], w.[WorksType]",
                           "  FROM [Characters] c" , 
                           "  INNER JOIN [Qualities] q ON c.ID = q.CharacterID",
                           "  INNER JOIN [Works] w ON c.ID = w.CharacterID",
                           "  ",
                           ")",
                           "SELECT TOP 10 c1.WorksType,",
                           "       SUM(CASE WHEN c1.Quality = c2.Quality THEN 1 ELSE 0 END) AS MatchCount", 
                           "FROM cte As c1",
                           "CROSS JOIN cte As c2",
                           "WHERE c1.ID < c2.ID",
                           " ",
                           "GROUP BY c1.WorksType",
                           "ORDER BY SUM(CASE WHEN c1.Quality = c2.Quality THEN 1 ELSE 0 END) DESC")

works_df <- retrieve_data(strSQL)
works_df <- within(works_df, WorksType <- factor(WorksType, levels=WorksType[order(-MatchCount)]))

ggplot(works_df, aes(WorksType, MatchCount, fill=WorksType)) + 
  geom_col(width=0.5) + 
  labs(title="Top 10 Matched By Works Type", y="Counts") + guides(fill=FALSE) +
  scale_fill_manual(values = seabornPalette) +
  scale_y_continuous(limits = c(0, 2000), expand=c(0,0), label=comma) +
  theme(plot.title = element_text(hjust = 0.5))

```

## Top 10 Works By Decade

```{r, fig.width=10, fig.height=5}
strSQL <-  strSQL <- paste("WITH cte AS (",
                           "  SELECT c.[ID], c.[Character], q.[Quality],", 
                           "         CAST(w.[YearCreated] / 10 AS INT) * 10 AS Decade",
                           "  FROM [Characters] c" , 
                           "  INNER JOIN [Qualities] q ON c.ID = q.CharacterID",
                           "  INNER JOIN [Works] w ON c.ID = w.CharacterID",
                           "  ",
                           ")",
                           "SELECT TOP 10 c1.Decade,",
                           "       SUM(CASE WHEN c1.Quality = c2.Quality THEN 1 ELSE 0 END) AS MatchCount", 
                           "FROM cte As c1",
                           "CROSS JOIN cte As c2",
                           "WHERE c1.ID < c2.ID",
                           " ",
                           "GROUP BY c1.Decade",
                           "ORDER BY SUM(CASE WHEN c1.Quality = c2.Quality THEN 1 ELSE 0 END) DESC")

decade_df <- retrieve_data(strSQL)
decade_df$Decade <- as.factor(decade_df$Decade)

ggplot(decade_df, aes(Decade, MatchCount, fill=Decade)) + 
  geom_col(width=0.5) + 
  labs(title="Top 10 Matched By Decade", y="Counts") + guides(fill=FALSE) +
  scale_fill_manual(values = seabornPalette) +
  scale_y_continuous(limits = c(0, 1200), expand=c(0,0)) +
  theme(plot.title = element_text(hjust = 0.5))
```

## Data Queries

```{r}
strSQL <- "SELECT c.Character, q.Quality
           FROM Characters c INNER JOIN Qualities q ON c.ID = q.CharacterID"
charqual_df <- retrieve_data(strSQL)

charqual_df$key <- 1
cross_join <- subset(merge(charqual_df, charqual_df, by="key"),
                     as.character(Character.x) < as.character(Character.y) & Quality.x == Quality.y)
cross_join[] <- sapply(cross_join, as.character)

agg_cross_df <- aggregate(key ~ Character.x + Character.y, cross_join, length)
reshape_df <- reshape(agg_cross_df, idvar="Character.x", v.names="key", timevar="Character.y", 
                      drop=c("Quality.x", "Quality.y"), direction="wide")

agg_df <- aggregate(key ~ Quality, charqual_df, length)
  
df_list <- by(charqual_df, charqual_df$Character, function(sub) {
  charname <- as.character(sub$Character[[1]])
  sub$key <- NULL
  
  tmp <- merge(agg_df[c("Quality")], sub, by="Quality", all.x=TRUE)
  tmp$Character <- ifelse(is.na(tmp$Character), NA, as.character(tmp$Quality))
  setNames(tmp, c("Character", charname))[-1]
})

lapply(df_list[sample(1:150, 5)], function(i) i[!is.na(i)])
```

## Pairwise Character Table

```{r, fig.width=10, fig.height=5}
x <- Filter(function(x) length(x) == 328, df_list)

g <- tableGrob(table(x$`Mr. Spock`, x$`Data`))
grid.arrange(g, left=textGrob("Mr. Spock"), bottom=textGrob("Data"),
             top=textGrob("Pairwise Character Matrix Table", gp=gpar(fontsize=20,font=3)))

g <- tableGrob(table(x$`Mr. Freeze`, x$`Captain Ahab`))
grid.arrange(g, left=textGrob("Mr. Freeze"), bottom=textGrob("Captain Ahab"),
             top=textGrob("Pairwise Character Matrix Table", gp=gpar(fontsize=20,font=3)))

g <- tableGrob(table(x$`Belle`, x$`Laura Wingfield`))
grid.arrange(g, left=textGrob("Belle"), bottom=textGrob("Laura Wingfield"),
             top=textGrob("Pairwise Character Matrix Table", gp=gpar(fontsize=20,font=3)))
```

## Select Character Heat Maps 

```{r, fig.width=10, fig.height=5}
raw <- table(Char1=cross_join$Character.x, Char2=cross_join$Character.y)

for (i in c("Bleeding Gums Murphy", "Barney Gumble", "Bartleby", "Alyosha", "Hamlet")) {
  print(i)
  sub <- subset(data.frame(raw), Char1 ==i)
  sub <- with(sub, sub[order(-Freq),])
  
  print(ggplot(data = sub[1:50,], aes(x=Char1, y=Char2, fill=Freq)) + geom_tile() + 
          labs(title="Heat Map Comparison", x="Select Character", y="Matching Characters") +
          theme(plot.title = element_text(hjust = 0.5)))
}
```

## Top 10 Quality Counts

```{r, fig.width=10, fig.height=5}
quality_df <- retrieve_data("SELECT * FROM Qualities")

agg_df <- setNames(aggregate(ID~Quality, quality_df, FUN=length), c("Quality", "Count"))
agg_df <- with(agg_df, agg_df[order(-Count),])
agg_df <- within(agg_df, Quality <- factor(Quality, levels=Quality[order(-Count)]))

ggplot(head(agg_df, 10), aes(Quality, Count, fill=Quality)) + 
  geom_col(width=0.5) + guides(fill=FALSE) +
  labs(title="All Characters Top 10 Qualities", y="Counts") +
  scale_fill_manual(values = seabornPalette) +
  scale_y_continuous(limits = c(0,max(head(agg_df, 10)$Count)+10), expand = c(0, 0)) +
  theme(plot.title = element_text(hjust=0.5, size=18))
```

## Pie / Donut Chart

```{r}
prop_df <- head(agg_df, 10)
prop_df$fraction <- prop_df$Count / sum(prop_df$Count)
prop_df <- with(prop_df, prop_df[order(fraction),])
prop_df$ymax <- cumsum(prop_df$fraction)
prop_df$ymin <- c(0, head(prop_df$ymax, -1))

prop_df
```

```{r, fig.width=10, fig.height=5}
ggplot(prop_df, aes(fill=Quality, ymax=ymax, ymin=ymin, xmax=4, xmin=3)) +
  geom_rect() + guides(fill=FALSE) + coord_polar(theta="y") +
  scale_fill_manual(values = seabornPalette) +
  geom_text(aes(label=Quality, x=3.85, y=(ymin+ymax)/2),
            inherit.aes = TRUE, show.legend = FALSE) +
  geom_text(aes(label=paste(round(fraction*100, 0),"%"), x=3.5, y=(ymin+ymax)/2),
            show.legend = FALSE) +
  labs(title="Top 10 Qualities Breakdown", y="", x="") +
  theme(panel.grid=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        plot.title = element_text(hjust = 0.5, size=18))
```

## Top 10 Qualities by Works Type

```{r, fig.width=10, fig.height=15}
works_df <- retrieve_data("SELECT * FROM works")
qualworks_df <- merge(quality_df, works_df, by="CharacterID", suffixes=c("", "_"))

qualplots <- by(qualworks_df, qualworks_df$WorksType, function(sub) {
  
  agg_df <- setNames(aggregate(ID~Quality, sub, FUN=length), c("Quality", "Count"))
  agg_df <- with(agg_df, agg_df[order(-Count),])
  
  agg_df <- within(agg_df, Quality <- factor(Quality, levels=Quality[order(-Count)]))
  
  ggplot(agg_df[1:10,], aes(Quality, Count, fill=Quality)) + 
    geom_col(width=0.5) + guides(fill=FALSE) +
    labs(title=paste("All Characters Top 10 Qualities\nfor", sub$WorksType[[1]], "Type"), y="Counts") +
    scale_fill_manual(values = seabornPalette) + 
    scale_y_continuous(limits = c(0,max(agg_df$Count)+1), expand = c(0, 0)) +
    theme(plot.title = element_text(hjust = 0.5, size=12),
          axis.text.x = element_text(angle = 23, hjust = 1))
})

do.call(grid.arrange, qualplots)
```

### Overall Top 10 Quality Counts

```{r, fig.width=10, fig.height=10}
agg_qw_df <- aggregate(ID ~ WorksType + Quality, qualworks_df, FUN=length)
agg_qw_df <- setNames(agg_qw_df, c("WorksType", "Quality", "Count"))
agg_qw_df <- with(agg_qw_df, agg_qw_df[order(-Count),])


ggplot(agg_qw_df[1:50,], aes(Quality, Count, fill=Quality)) + 
  geom_col(width=0.5) + guides(fill=FALSE) +
  labs(title="All Characters Top 50 Qualities By Works Type", y="Counts") +
  scale_fill_manual(values = seabornPalette) +
  scale_y_continuous(expand = c(0, 0)) +
  theme(plot.title = element_text(hjust = 0.5, size=18),
        axis.text.x = element_text(angle = 23, hjust = 1)) + 
  facet_wrap(~WorksType, scales="free_x", ncol=2)

```

