CREATE TABLE CHARACTERS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CHARACTER VARCHAR(255),
    DESCRIPTION VARCHAR(1500),
    QUOTE VARCHAR(1500),
    LINKIMAGE VARCHAR(255),
    PICTURE BLOB(800K),
      PRIMARY KEY (ID)
);

CREATE TABLE QUALITIES (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CHARACTERID INTEGER,
    QUALITY VARCHAR(255),
    SPECIAL BOOLEAN,
      PRIMARY KEY (ID),
      FOREIGN KEY CHAR_KEY (CHARACTERID)
      REFERENCES CHARACTERS ON DELETE NO ACTION
);

CREATE TABLE WORKS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CHARACTERID INTEGER,
    TITLE VARCHAR(255),
    CREATOR VARCHAR(255),
    YEARCREATED INTEGER,
    YEARPERIOD VARCHAR(5),
    WORKSTYPE VARCHAR(255),
    COMPANY VARCHAR(255),
    OTHERCREATOR VARCHAR(255),
      PRIMARY KEY (ID),
      FOREIGN KEY CHAR_KEY (CHARACTERID)
      REFERENCES CHARACTERS ON DELETE NO ACTION
);

CREATE LOB TABLESPACE CHARS_PIC_SPACE
    IN MEEKNESS
    LOG ON;
COMMIT;
CREATE AUXILIARY TABLE CHARS_PIC_AUXTAB
    IN MEEKNESS.CHARS_PIC_SPACE
    STORES CHARACTERS
    COLUMN PICTURE;
CREATE UNIQUE INDEX CHARS_PIC_IDX
    ON CHARS_PIC_AUXTAB;
COMMIT;


